### ISSUE TITLE
Show city names in modals and routes

### ISSUE THREAD

**Issue by Auzzy** [Auzzy/1846-routes-web#13]
Since every city has a name, it would provide some useful grounding to show that name. Maybe also include the coordinate. This should be done both in the input dropdowns and in the best routes modal.

**Comment by byronczimmer** [comment]
Recommend that user be allowed to toggle this on/off for each use (entry/output)

**Comment by michaeljb** [comment]
I would love to see this feature, particularly for the route calculation. I think it would also be useful to show how much is earned in each city, e.g., "Chicago Connections (90), Chicago (90), ..."

**Comment by Auzzy** [comment]
> I think it would also be useful to show how much is earned in each city, e.g., "Chicago Connections (90), Chicago (90), ..."

I'll see how it looks when I do so. Maybe I'll have a toggle to turn it on and off. I'll play around with it and see.

**Comment by Auzzy** [comment]
Deployed across a couple commits:
- https://github.com/Auzzy/1846-routes-web/commit/c178ff411ae579a4faa1a40d885f2dfb65bbbbdb - When a route is calculated, the list of cities visited and their values are displayed. To help visually separate routes, the full route is bolded. The city list can be disabled by clicking the link above. That setting persists across sessions.
- https://github.com/Auzzy/1846-routes-web/commit/c7b94e0f247f5cfe642cd6ebe1fe76aecc5f7358 - The name of the city is added to the header of the tile selection modal, with the coordinate in parens.
- https://github.com/Auzzy/1846-routes-web/commit/4f4a3a4c149050524de2fd2c923ef39743620aa4 - Display city name (and coordinate) in the stations table and modal.
- https://github.com/Auzzy/1846-routes-web/commit/072d9e65163aa632a40d23c82343a92f726dc39a - Display city name (and coorindate) in the private companies table and dropdowns.

Let me know if you have any comments about the change. I'm debating whether its worth adding the ability to toggle off the coordinates, for example.
