### ISSUE TITLE
Place stations via the map

### ISSUE THREAD

**Issue by Auzzy** [Auzzy/1846-routes-web#18]
The user should be able to click on the map to place stations. Ideally, the station token would also appear on the map, although that may be somewhat tricky to do in a way that looks good.

**Comment by mugnaio** [comment]
thank you for adding this, I think it would be the best improvement of this great project.

**Comment by Auzzy** [comment]
This was deployed across a number of smaller commits:
- https://github.com/Auzzy/1846-routes-web/commit/1d27529925422a32502aa1de9f439417ada3b404 added tabbing to the tile selection modal.
- https://github.com/Auzzy/1846-routes-web/commit/95d2880ce97f59c88b0add170458d09a07d7c16d displays the stations in the modal
- https://github.com/Auzzy/1846-routes-web/commit/c2043b70f33c60929aedd99cd361319aa98aab84 - hides the stations tab on track tiles.
- https://github.com/Auzzy/1846-routes-web/commit/f50824c0c76863a312c8a1c49cf9a2a75f8dd96b allows adding and removing stations
- https://github.com/Auzzy/1846-routes-web/commit/8c866d837992f75e910097e17751c09429584be8 handles Chicago's special casing
- https://github.com/Auzzy/1846-routes-web/commit/1e9fad6aeb4697c965cf9f644c6a6e2ffd2a7911 handles Centralia (I5) special casing.

**Comment by Auzzy** [comment]
Note that I intentionally left out any capacity check for now. This is to allow you to easily change tiles without having to worry about capacity (e.g. placing a phase 2 instead of phase 1). I may do some sort of capacity checking eventually, but it's not the highest priority.

**Comment by Auzzy** [comment]
Just deployed 2 small improvements to this.
* https://github.com/Auzzy/1846-routes-web/commit/a9a6e5062283a50c9e34eaf90a975e75785e6db9 - Display independent railroads in the stations tab of the tile selection modal. Of course, they're only shown if no one owns them, and it's phase 1 or 2.
* https://github.com/Auzzy/1846-routes-web/commit/bd6900d1ffc6c9100ec634da46766bfb396088ab - Hides the delete button for the major railroad's station which replaces an acquired independent railroad station.
