### ISSUE TITLE
"An error occurred during route calculation: 'Chicago' object has no attribute 'get_station_exit_cell' "

### ISSUE THREAD

**Issue by cdeguide** [Auzzy/1846-routes-web#20]
Whenver attempting to calculate a route for the Illinois Central Railroad, the following error occurs: An error occurred during route calculation: 'Chicago' object has no attribute 'get_station_exit_cell'

This happens even though the Chicago exit cell is correctly selected, the issue does not occur for the other 2 companies in the game, and the error only began occuring after a route to Chicago was completed, previously ICR had a token in Chicago not connected to anything except a piece of track in E7, and the error did not occur. 

Current Tile Layout:

J4 | 9 | 0
-- | -- | --
I3 | 9 | 1
G5 | 27 | 4
I7 | 9 | 1
G7 | 15 | 1
G9 | 57 | 1
D18 | 8 | 0
E17 | 292 | 3
C13 | 7 | 5
B16 | 6 | 2
D14 | 15 | 5
E13 | 8 | 3
I9 | 8 | 1
E15 | 25 | 4
B10 | 9 | 1
B12 | 9 | 4
B14 | 8 | 3
G11 | 8 | 1
E7 | 8 | 2
H6 | 8 | 2
G3 | 6 | 0
H12 | 291 | 3
G13 | 6 | 0
E11 | 57 | 1
G15 | 5 | 2
F14 | 8 | 5
F6 | 8 | 5

Railroads: 

Illinois Central | 2 | 2 | 3 / 5 |   | D6,I5,K3 | E7
-- | -- | -- | -- | -- | -- | --
Baltimore & Ohio | 2 | 2 | 2 | 4 | G9,G19,H12 |  
New York Central | 2 | 2 | 3 / 5 | 3 / 5 | D20,G13 |

**Comment by Auzzy** [comment]
There was a bug in the handling of the Chicago tile when it wasn't upgraded. So once it was connected, it became a viable route option, and the error occurred.

I just deployed the fix, and tested it with your data, and all seems well. Thanks for the report!
