### ISSUE TITLE
BUG: Calculate button requires a track to be laid

### ISSUE THREAD

**Issue by byronczimmer** [Auzzy/1846-routes-web#3]
Data entered:
No track
B&O Station at G19
Steamboat owend by B&O at G19
B&O owns 1 "2" train.

Calculate button cannot be clicked.

**Comment by Auzzy** [comment]
This issue actually has nothing to do with the Steamboat Company. The Calculate button requires at least one track be laid to be enabled. I'm going to rename this bug to reflect that.

**Comment by Auzzy** [comment]
Fix deployed in commit 0fbcf100a87dd106a338d9de7e1348dcb90dda1c
