### ISSUE TITLE
Private company name cel should not be deleteable

### ISSUE THREAD

**Issue by mugnaio** [Auzzy/1846-routes-web#41]
If (for mistake) i delete the name of a private company there is no way to easily add it again (actually I find out you could "control+V" its name on the cell and it seems to work)

**Comment by Auzzy** [comment]
I will be redesigning this table soon (#35), so I'm not going to spend too much time on this issue. But I'll take a look to see if it can be prevented with little effort.

**Comment by Auzzy** [comment]
Deployed this fix in 0731a0e396357a0e293bc96d01abc84302cd7036.

In addition to preventing deletion of the name, I also restore the cell names after loading from local storage. This way, if anyone has already deleted those cells, refreshing the page will bring them back.
