### ISSUE TITLE
Display Steamboat value

### ISSUE THREAD

**Issue by Auzzy** [Auzzy/1846-routes-web#72]
Some Steamboat Company cities are worth $20, some are worth $40. However, I display the same single token regardless. I'd like to visually represent the difference somehow. I think displaying 2 tokens will look like a glitch, and won't look great. Displaying the value on the token will be tricky as they're already small. So I'll need to play around with this.

**Comment by wcraigtrader** [comment]
There are only two towns (Wheeling and Holland) where this presents a problem, and for the physical map, both are indicated by using 2 anchor icons, so I don't think it would be confusing to show 2 icons in your tool.
