### ISSUE TITLE
Michigan Southern cannot use the Steamboat Company token in Toledo

### ISSUE THREAD

**Issue by wcraigtrader** [Auzzy/1846-routes-web#74]
The player that owns the Steamboat Company can assign its token to any railroad (including the independent railroads) without it being owned by a company. The UI doesn't allow the Michigan Southern to take advantage of the Steamboat token in Toledo.

Of course the UI doesn't allow the MS or Big4 to own a train, or calculate routes, either, so that might not be a design goal.

**Comment by Auzzy** [comment]
Since the MS and Big4 can only have a single 2-train, running routes with them in this tool is likely overkill. As you surmised, that's why I didn't allow them to be assigned Steamboat Company or Meat Packing Company.
